@startuml activity

title Получение случайной команды

actor "Пользователь" as User
boundary "Приложение" as App
database "Файл со списком экипировки" as DB

User --> App++ : Выставление нужных настроек
User --> App   : Запрос об рандомизации
App --> App    : Рандомизация бойцов
App --> App    : Получить уровень пользователя
App --> DB++   : Прочитать возможную экипировку
DB --> App--
App --> App    : Получение случайной экипировки
App --> User-- : Вывод результата

@enduml