all:
	gcc main.c ../../../MyLibs/C_Lib/functions.c -o main -pthread --std=gnu11
	./main
compile:
	gcc main.c ../../../MyLibs/C_Lib/functions.c -o main -pthread --std=gnu11
debug:
	gcc main.c ../../../MyLibs/C_Lib/functions.c -g -o main -pthread --std=gnu11
clear:
	rm -rf main