@startuml activity

title Получение случайной команды

start

label start
(A)
while (отряд соситоит из четырех бойцов?) is (нет)
    label start
    :Получить бойца;

    if (Полученный боец доступен для рандома?) then (да)
        if (Полученный боец еще не находиться в отряде?) then (да)
            :добавить бойца в отряд;
            (C)
            while (пока не выдано четыре способности) is (Истинна)

                :Получить случайную способность;
                if (такая способность уже выдана?) then (да)
                    (C)
                endif
                :Выдать способность бойцу;
            endwhile (способности выданы)
        else (нет)
            (A)
        endif
    else (нет)
        (A)
    endif
endwhile (комманда укомплектована)


:Получить уровень пользователя;
:Получить список доступного вооружения;
(B)
while (эикипировка есть у всех бойцов?) is (нет)

    :Получить предмет из списка экипировки;

    if (полученный предмет возможно кому-нибудь дать?) then (да)
        :выдать предмет бойцу;
    else
        (B)
    endif

endwhile (экипировка выдана)
:Выввести комманду на экран;
stop

@enduml