@startuml

title Состояние окна

[*] --> Окно            : Пользователь открыл программу

Окно --> Параметры      : Пользователь выставляет свои параметры
Параметры --> Окно      : На окне отображаются изменения

Окно --> Рандомизация   : Пользователь нажал на кнопку рандома
Рандомизация --> Окно   : Программа выводит результат

Окно --> [*]            : Пользователь закрыл программу

@enduml