@startuml scheme
!define Table class
!define PKField {field} : PK
!define FKField {field} : FK

' Notes:
' Zero or One 	|o--
' Exactly One 	||--
' Zero or Many 	}o--
' One or Many 	}|--

' Main objects

Table Сотрудник {
	+ ФИО (PK)
	--
	Название должности (FK)
	Начало рабочего дня
	Конец рабочего дня
	Зарплата
}

Table Должность {
	+ Название должности (PK)
	--
	Обязанности
}

Table Кинозал {
	+ Название кинозала (PK)
	--
	Номер зала
	Количество мест
	Назначенный работник (FK)
}

Table Клиент {
	+ ФИО (PK)
	--
	Номер билета
	Email
}

Table Фильм {
	+ Название фильма (PK)
	--
	Жанры
	Оценка критиков
}

Table "Актёрский cостав" {
	+ ФИО (PK)
	--
	Рейтинг
	Возраст
}

' their connections

Должность --|{ Сотрудник
Сотрудник --|{ Кинозал
"Актёрский cостав" }|--|{ Фильм

' complex object

Table Бронирование {
	+ Название кинозала (PK, FK1)
	+ ФИО килента (PK, FK2)
	+ Название фильма (PK, FK3)
	+ Номер активного бронирования (PK)
	--
	Дата
	Номер места
	Номер ряда
}

Кинозал }--{ Бронирование
Фильм }--{ Бронирование
Клиент --|{ Бронирование

@enduml
